name: fficxx
version: '0.2.999'
synopsis: automatic C++ binding generation
description: automatic C++ binding generation
category: FFI Tools
author: Ian-Woo Kim
maintainer: Ian-Woo Kim <ianwookim@gmail.com>
license: BSD3
git: http://www.github.com/wavewave/fficxx
ghc-options:
- -Wall
- -funbox-strict-fields
- -fno-warn-unused-do-bind
ghc-prof-options:
- -caf-all
- -auto-all
dependencies:
- base ==4.*
- Cabal
- bytestring
- containers
- data-default
- directory
- either
- errors
- filepath >1
- hashable
- haskell-src-exts
- lens >3
- mtl >2
- process
- pureMD5
- split
- transformers >=0.3
- template
- template-haskell
- text
- unordered-containers
library:
  source-dirs: lib
  exposed-modules:
  - FFICXX.Generate.Builder
  - FFICXX.Generate.Type.Class
  - FFICXX.Generate.Type.Module
  - FFICXX.Generate.Type.PackageInterface
  - FFICXX.Generate.Config
  - FFICXX.Generate.Code.MethodDef
  - FFICXX.Generate.Code.Cpp
  - FFICXX.Generate.Code.HsFrontEnd
  - FFICXX.Generate.Code.HsFFI
  - FFICXX.Generate.Code.Cabal
  - FFICXX.Generate.Code.Dependency
  - FFICXX.Generate.Generator.Driver
  - FFICXX.Generate.Generator.ContentMaker
  - FFICXX.Generate.Util
  - FFICXX.Generate.Util.HaskellSrcExts
  - FFICXX.Generate.QQ.Verbatim
  - FFICXX.Generate.Type.Annotate
  - FFICXX.Paths_fficxx
data-files:
- sample/cxxlib/include/*.h
- sample/cxxlib/src/*.cpp
- sample/cxxlib/Makefile
- sample/mysample-generator/MySampleGen.hs
- sample/mysample-generator/use_mysample.hs
- sample/snappy-generator/SnappyGen.hs
- sample/snappy-generator/testSnappy.hs
